### ISSUE TITLE
Please make a postgresql setup(integration with the backend) in the development section of contributing.md

### ISSUE THREAD

**Issue by BidemiEnoch** [Tekipeps/aul-forum#30]

**Comment by Tekipeps** [comment]
okay..

**Comment by Tekipeps** [comment]
I put a link to donwload postgres from its website
Not sure the installation steps on windows

but after installation the steps to connect to the database is there
![image](https://user-images.githubusercontent.com/45674928/110878188-0350ae80-82db-11eb-9b91-ee2bc8f88b84.png)

**Comment by EmeditWeb** [comment]
seeing strange things 😒😒🙄
