### ISSUE TITLE
Please lets use a specific typing convention

### ISSUE THREAD

**Issue by BidemiEnoch** [Tekipeps/aul-forum#42]
https://github.com/Tekipeps/aul-forum/blob/react-ts/client/src/services/auth_service.ts, please lets avoid inline type declarations like `{ username, password }: { username: string; password: string }`, not bad, just harder to read,(esp when youre destructuring a long list of items) Ill make a pr doing this with an interface, so lets stick to interfaces for long parameter lists, nice update by the way, login.tsx looks sexy asf

**Comment by Tekipeps** [comment]
lmao..
its cool.. you can create a Login interface and use it
tag this issue in the pr
