### ISSUE TITLE
Remove login and register from nav after login

### ISSUE THREAD

**Issue by Tekipeps** [Tekipeps/aul-forum#59]
need to remove login and register buttons from main navigation after login

also the theme toggle button should be on the main navigation bar 

![image](https://user-images.githubusercontent.com/45674928/112234659-485ed400-8c3d-11eb-8ab4-10a39fe760e7.png)

**Comment by BidemiEnoch** [comment]
yah, there should be 5 routes in total
home 
profile
about 
login
register
login and register should disappear after login, I renamed team to about , I will be working on that particular page for a while

**Comment by BidemiEnoch** [comment]
The update you made however only redirects from login/register if the user is logged in, hoping this isnt permanent

home - login - register - about should transform to
home - profile - about after login. Whether the logout btn should be in nav bar or profile section idk...

**Comment by BidemiEnoch** [comment]
Whichever im working on the /about page, it would fetch some data about this repo and its contributors with the github api and display it, so people can see who has contributed the most, view the creation, last modified timestamps of this repo e.t.c
maybe you should work on the routing, or should I? idk. currently workiing on /about whichever way

**Comment by Tekipeps** [comment]
> The update you made however only redirects from login/register if the user is logged in, hoping this isnt permanent
> 
> home - login - register - about should transform to
> home - profile - about after login. Whether the logout btn should be in nav bar or profile section idk...

You can add the logout button on the top navigation after about
