### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by BidemiEnoch** [Tekipeps/aul-forum#64]
api/auth/isvalidtoken gives an access denied error if the user isn't logged in, but still /login or /register redirects to home if the user *isn't logged in*. Creating a new user also returns some 'could not clone object error'. Idk if this something from my end or... ?

**Comment by Tekipeps** [comment]
test the route with postman..
your backend server have to be up for it to work

**Comment by Tekipeps** [comment]
I have to setup redux to handle the errors appropriately.. I should do that before Sunday

**Comment by BidemiEnoch** [comment]
> 
> 
> test the route with postman..
> your backend server have to be up for it to work

yh ive set the backend server lol.
after debugging i realized...
``if(token && validateToken(token){}``
always evaluates to true even if token is null(The user has not logged in)

**Comment by BidemiEnoch** [comment]
Also I would appreciate if there was a neater way to check if the user is logged in,*instead of repeating the same code over* like a neat `auth.userIsLoggedIn()` function wrapper, that way I can work on dynamic routing, 
- display login register if not logged in,
- if logged in remove register and login from nav bar, display profile-home, redirect /register and /login to /logout when the url is manually entered

**Comment by Tekipeps** [comment]
fixed validation errors in this commit [0c51a22](https://github.com/Tekipeps/aul-forum/commit/0c51a222f90d7e10e804201f0ead961b939e1cfc)
