### ISSUE TITLE
Please document your changes properly

### ISSUE THREAD

**Issue by BidemiEnoch** [Tekipeps/aul-forum#9]
1. "scripts": {
        "start": "NODE_ENV=production node index.js",
        "dev": "NODE_ENV=development nodemon index.js"
    } works on linux not windows,
"scripts": {
        "start": "set NODE_ENV=production && node index.js",
        "dev": "set NODE_ENV=development && nodemon index.js"
    }, is the workaround on windows
2. Should have specified that dependencies should have been reinstalled, Ran into dotenv and prisma-cli not installed errors, before i realized they were new dependencies
3. explain the creation of the environment variables better (.env file and any other related file) better, currently poorly explained

**Comment by Tekipeps** [comment]
Yeah if you notice changes in package.json you should always rerun `yarn` or `yarn install`
